### ISSUE TITLE
Where can I store "global" drivers?

### ISSUE THREAD

**Issue by mikeerickson** [tinkerwellapp/drivers#14]
I would like to create a global driver which is available in any Laravel application.  This drive will ultimately want to create files in the current project directory.

This driver will be very similar to the Artisan driver, but instead it will work with our [Laraval Craftsman](https://github.com/mikeerickson/laravel-craftsman) utility.

**Comment by mpociot** [comment]
That's not possible with the current version of Tinkerwell
I'll add the ability to store global drivers somewhere (like Valet does with a `~/.config/valet/Drivers` path in a next release 👍

**Comment by mikeerickson** [comment]
Hey Marcel

Was this added?  I am using v2.2.1 and do see any specific reference in
upgrade notes, etc for global drivers?

Mike Erickson
codedungeon@gmail.com

**Comment by tylerwiegand** [comment]
Also was hoping for this due to the new release for Laravel 7 recently. I don't wanna commit .tinkerwell folders to all my projects! Pleasseeeee =)

**Comment by JoshMoreno** [comment]
Hey @mpociot , looks like this was [released under 2.6.0](https://tinkerwell.app/release/2.6.0). P.S. the page title reads `2.5.0`.

For anyone else that finds this, add your custom global drivers in your `~/.tinkerwell` directory.

**Comment by johanvanhelden** [comment]
@JoshMoreno what O.S. are you using? I tried to do this on Linux, but it does not work :confused:

**Comment by mechelon** [comment]
See https://github.com/tinkerwellapp/drivers/issues/14#issuecomment-613577299
