### ISSUE TITLE
Inclusion of `bootstrap` method throws error

### ISSUE THREAD

**Issue by mikeerickson** [tinkerwellapp/drivers#16]
I am testing a very simple driver, and when I include the `bootstrap` method, it causes an error when loading custom project.  

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/183153/74091622-3e483900-4a6e-11ea-8ce6-9dcca173234d.png">

If I remove the `bootstrap` method, everything works as expected.

The simple driver code (basically pulled from example below)

```php
<?php

use Tinkerwell\ContextMenu\SetCode;

class CustomTinkerwellDriver extends LaravelTinkerwellDriver
{

    public function canBootstrap($projectPath)
    {
        var_dump("canBootstrap ${projectPath}");
        return true;
    }

    // if function is removed, all works as expected
    public function bootstrap($projectPath)
    {
    }

    public function contextMenu(): array
    {
        return array_merge(parent::contextMenu(), [
            SetCode::create('Find latest users', <<<EOT
User::latest()->first()
EOT
            ),
        ]);
    }

}
```

**Comment by mpociot** [comment]
The problem is that you are extending from the Laravel driver, but since you override the `bootstrap` method, you never call the origin driver's bootstrap code.

Either remove the method, or call the parent bootstrap method with your own custom code.
