### ISSUE TITLE
SetCode `insert` method

### ISSUE THREAD

**Issue by mikeerickson** [tinkerwellapp/drivers#17]
In reviewing the SetCode class methods, I only see the ability to `create` code, which overwrites the entire code area.   Is there the ability to insert code at the current cursor position?

Example

```php
SetCode::insert("codeToAdd");
```

Or further, get the highlighted code and replace with new code

```php
SetCode::replace("codeToReplace");
```

**Comment by musa11971** [comment]
Duplicate of: https://github.com/tinkerwellapp/drivers/issues/11

@mpociot Any information on this? 😃

**Comment by mpociot** [comment]
That's currently not possible, but meanwhile I added a new `RunCode` context-menu entry, which will not display the code but evaluate it immediately. So it will not modify the input text area.
