### ISSUE TITLE
Custom Drivers Require the name "TinkerwellDriver.php" to load

### ISSUE THREAD

**Issue by deek87** [tinkerwellapp/drivers#2]
In the documentation it makes no mention of the suffix of TinkerwellDriver.php but in the code of tinkerwelldriver.php it becomes apparent to load a driver you need to call you driver
xxxx-TinkerwellDriver.php

Because of this line  https://github.com/tinkerwellapp/drivers/blob/e0ff463ebd948517ee6b5e621f9b4f7cddd93c59/src/Drivers/TinkerwellDriver.php#L78

Im not sure if you want to clarify this in the readme or allow the loading of *Driver.php

**Comment by mpociot** [comment]
Good point, thanks for the heads up!
I updated the readme
