### ISSUE TITLE
Unable to connect to local Valet WordPress site. 

### ISSUE THREAD

**Issue by joedooley** [tinkerwellapp/drivers#24]
It's not a standard WP installation. We use Composer to pull in WP as a dependency. The installation is similar to what's described [here](https://composer.rarst.net/recipe/site-stack/).

The app is throwing this [warning](https://d.pr/i/EhTQuK).

The path to composer's `vendor` directory is `wp-content/vendor/autoload.php`.

I upgraded to Version 2.2.0 (2.2.0) just now but that didn't help. Also running the latest version of MacOS, 10.15.3. Laravel Valet is up to date as well.

Any suggestions? Thanks in advance.

**Comment by mpociot** [comment]
You will most likely need a custom driver, that loads the autoloader in your location.
If no driver can be detected, Tinkerwell automatically loads the composer autoloader from `vendor/autoload.php`
