### ISSUE TITLE
Lumen Driver not working for me

### ISSUE THREAD

**Issue by xitox97** [tinkerwellapp/drivers#26]
Hello guys, Im still new using Tinkerwell. It works well in Laravel App, but in Lumen its a bit weird.

For example: If I tried to used Eloquent to get first data in modal. I did not get the data instead I only get the properties of the modal ![Image of Yaktocat](https://i.imgur.com/S9Tp6Kh.png).

For second problem is, In Laravel app, If I tried to open query inspection(Ctrl + Shift + R) I got this error ![Image of Yaktocat](https://i.imgur.com/vyaqNSN.png)

Im using on Windows.

**Comment by nkback** [comment]
@xitox97 What'd you do to get your Lumen driver to work? I can't seem to get it to work on version 2.2.1 of Tinkerwell.

**Comment by xitox97** [comment]
@nkback  just add ->toArray or ->toJson after you do anything that contains data. then only it will display.

https://snipboard.io/zxETys.jpg

**Comment by nkback** [comment]
Hmmm. My problem seems to be different. What'd you add to your project to get Lumen working in Tinkerwell? 

I have the LumenTinkerwellDriver.php in a .tinkerwell directory, and I'm getting this error:
![image](https://user-images.githubusercontent.com/21178956/75005648-491aaa80-542c-11ea-8338-8eb8f6b8dac0.png)

**Comment by xitox97** [comment]
@nkback ouhh, I just upgrade my php version to 7.3. and then on setting > advanced tab > select path for the php binary.
![image](https://user-images.githubusercontent.com/15958161/75033045-edf8be80-54e4-11ea-95e4-6e9ff5478e91.png)
