### ISSUE TITLE
Cascaded driver loading?

### ISSUE THREAD

**Issue by ikari7789** [tinkerwellapp/drivers#29]
I think there is a possible issue with how driver's are loaded?

I'm attempting to load a Lumen project, but it seems to be attempting to load it as a Laravel application.

I get the following error.

```shell
In LaravelTinkerwellDriver.php line 24:
                                                                             
  Call to undefined method App\Console\Kernel::bootstrap()  
````

I'm not sure how drivers are loaded exactly or how the driver is determined beyond what I see in the existing code, but a Lumen application fits the parameters of `canBootstrap()` for both `LaravelTinkerwellDriver` and `LumenTinkerwellDriver` and since Laravel comes before Lumen alphabetically, it's my guess that it attempts to load LaravelTinkerwellDriver, and then fails, and doesn't have anyway to try the next driver.

- Is driver loading cascaded at all if it fails to load one, and will attempt to load another if it fits?
- Is there anyway to force a specific driver?

**Comment by mpociot** [comment]
The way it works right now is, that we loop through all available drivers and the first driver that returns `true` for `canBootstrap` will be used.

The problem only occurs with the Lumen and Laravel drivers though, so maybe we can just come up with a more specific way of differentiating between those two drivers.

Right now, specific drivers can only be forced by adding them to your local project as in a `.tinkerwell` folder.
