### ISSUE TITLE
How to test/debug local drivers?

### ISSUE THREAD

**Issue by skydiver** [tinkerwellapp/drivers#3]
I've created `.tinkerwell/MyCustomTinkerwellDriver.php` on my project but doesn't appear to load.

* There is an "official" way to locally test drivers before PR?
* There is any way to debug drivers?

**Comment by maks-rafalko** [comment]
I have debugged it with `var_dump()` from driver itself, see https://github.com/tinkerwellapp/drivers/issues/6

**Comment by edalzell** [comment]
Ya where do the file(s) go to see if it works?

The instructions don't say where/how to start a new driver.

**Comment by maks-rafalko** [comment]
https://github.com/tinkerwellapp/drivers#project-specific-drivers

you can create `.tinkerwell` folder in the root of your project and locate custom driver there
