### ISSUE TITLE
[Feature request] "public_html" support

### ISSUE THREAD

**Issue by johanvanhelden** [tinkerwellapp/drivers#30]
In some hosting environments `public_html` is used instead of `public`.

Currently, the `public` folder is hard-coded in the Laravel driver:
https://github.com/tinkerwellapp/drivers/blob/master/src/Drivers/LaravelTinkerwellDriver.php#L12

So at this moment for these projects, Tinkerwell can not be used without writing a custom driver for the projects that have a `public_html` folder.

Possible fixes:
- Only check for the existence of `artisan` and ignore the webroot folder.
- Check for both `public` and `public_html`
- ...

For now there is a work-around by including a custom driver that is a copy of the Laravel driver and has the path changed, but it is my opinion extra overhead, dirties repo's and should be working out-of-the-box.

**Comment by sschlein** [comment]
We don't have plans to support non-standard application setups via the official drivers. This makes detection for other frameworks more difficult and creates a maintenance overhead over the long term that we don't want to handle.

We will introduce global drivers (https://github.com/tinkerwellapp/drivers/issues/14) in the future to solve this issue and don't pollute repositories.

So the project-based driver is not a workaround but the recommended way to handle custom application setups.
