### ISSUE TITLE
Custom crypto binding not available - Can't connect to remove server

### ISSUE THREAD

**Issue by octoxan** [tinkerwellapp/drivers#53]
For our works development environments, we're using Coder.com and it aliases connections as `coder.workspacename` so if I have a workspace called example, in any terminal on my machine I can type `ssh coder.example` and connect just fine.

This also works in TablePlus, SQL Pro Studio, VS Code, etc.

When I try to tell Tinkerwell to connect to a domain like this, it throws the following error:

```
Custom crypto binding not available
Local ident: 'SSH-2.0-ssh2js1.10.0'
Client: Trying coder.example on port 22 ...
Socket error: getaddrinfo ENOTFOUND coder.example
```

These servers are used to run remote Laravel development environments so being able to connect to them with Tinkerwell would be greeeeeat.

**Comment by michaelklopf** [comment]
Well, if anyone encounters this issue, you shouldn't change the port away from 22 and be sure to use the correct private key.

**Comment by sschlein** [comment]
@michaelklopf when using port 22 and a correct key, coder.com works?

If you can confirm that, I'll set up a test account there and do a short blog post for documentation purposes soon.

**Comment by mechelon** [comment]
I will close this issue due to inactivity.
