### ISSUE TITLE
Please implement these menus shortcut key: next tab and previous tab

### ISSUE THREAD

**Issue by pys1992** [tinkerwellapp/drivers#57]
Such as the following app postman. I can use shortcut key to switch tab.

<img width="791" alt="image" src="https://github.com/tinkerwellapp/drivers/assets/44765369/dc342ce0-92db-488f-9afe-a20fff8f3933">

**Comment by mechelon** [comment]
Besides that this is not the repository for the tinkerwell.app software, but for it's drivers - that's already possible. You can either cycle through tabs with CTRL+Tab or go to the next/previous tab with CTRL+PageDown/PageUp.
